name: Challenge
authors: [ Rysefoxx ]
version: '${project.version}'
api-version: 1.20
main: io.github.rysefoxx.core.ChallengePlugin
libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.5.4-DEV